- name: Install dnf Packages
  ansible.builtin.package:
    name: "{{ dnf_pkgs }}"
  when: ansible_facts['os_family'] == "RedHat"
  become: true

- name: Install apt Packages
  ansible.builtin.package:
    name: "{{ apt_pkgs }}"
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Symlink to user
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  when: ansible_facts['os_family'] == "Debian"
  loop:
    - { src: /usr/bin/batcat, dest: ~/.local/bin/bat }
    - { src: /usr/bin/fdfind, dest: ~/.local/bin/fd }
