- name: Dot files config
  hosts: local
  pre_tasks:
    - name: Update Cache
      ansible.builtin.dnf:
        update_cache: true
        state: present
      when: ansible_facts['os_family'] == "RedHat"
  roles:
    - role: git
      tags: git
      vars:
        git_email: enoch965@gmail.com
        git_user: ec965
    - role: zsh
      tags: zsh
      vars:
        zdotdir: ~/.config/zsh
    - role: tmux
      tags: tmux
    - role: devtools
      tags: devtools
      vars:
        homebrew_pkgs:
          - ansible
          - bat
          - fd
          - fzf
          - git-delta
          - jq
          - python
          - ripgrep
          - stylua
          - kubectx
          - defaultbrowser
        homebrew_casks:
          - alacritty
          - linearmouse
          - rectangle
          - spaceid
        dnf_pkgs:
          - bat
          - fd-find
          - fzf
          - git-delta
          - jq
          - podman
          - podman-compose
          - python
          - ripgrep
          - wget
          - zip
        apt_pkgs:
          - bat
          - fd-find
          - fzf
          - jq
          - ripgrep
          - wget
          - zip
    - role: mise
      tags: mise
    - role: nodejs
      tags: nodejs
      vars:
        npm_global_packages:
          - prettier
          - typescript
          - yarn
    - role: nvim
      tags: nvim
    - role: vscode
      tags: vscode
    - role: fonts
      tags: fonts
    - role: alacritty
      tags: alacritty
      vars:
        font_size: 15
        font: FantasqueSansM Nerd Font
        opacity: 0.85
    - role: skhd
      tags: skhd
      when: ansible_facts['os_family'] == "Darwin"
