- name: Dot files config
  hosts: local
#  pre_tasks:
#    - name: Update Cache
#      ansible.builtin.dnf:
#        update_cache: true
#        state: present
#      when: ansible_facts['os_family'] == "RedHat"
  roles:
    - role: git
      tags: git
      vars:
        git_email: enoch965@gmail.com
        git_user: enochchau
    - role: zsh
      tags: zsh
      vars:
        zdotdir: ~/.config/zsh
    - role: tmux
      tags: tmux
    - role: devtools
      tags: devtools
      vars:
        homebrew_pkgs:
          - bat
          - fd
          - fzf
          - git-delta
          - jq
          - ripgrep
        homebrew_casks:
          - rectangle
        dnf_pkgs:
          - bat
          - fd-find
          - fzf
          - git-delta
          - jq
          - ripgrep
        apt_pkgs:
          - bat
          - fd-find
          - fzf
          - jq
          - ripgrep
    - role: nvim
      tags: nvim
    - role: mise
      tags: mise
    - role: nodejs
      tags: nodejs
      vars:
        npm_global_packages:
          - prettier
    - role: vscode
      tags: vscode
    - role: ghostty
      tags: ghostty
#    - role: fish
#      tags: fish
