#!/bin/zsh
# set editor to nvim
export VISUAL=nvim
export EDITOR="$VISUAL"

# setup XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

if [ -e /home/enoch/.nix-profile/etc/profile.d/nix.sh ]; then . /home/enoch/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
