- name: Install mise Mac
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: "mise"

- name: Enable Mise COPR Repo
  when: ansible_facts['os_family'] == "RedHat"
  community.general.copr:
    name: jdxcode/mise
    state: enabled
  become: true
- name: Install mise Linux
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.package:
    name: "mise"
  become: true
    
- name: Link mise config
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/mise/files/"
    path: "~/.config/mise"
    state: link

- name: Install mise
  ansible.builtin.shell: mise install
