require("enoch.cmp")
require("enoch.filetree")
require("enoch.gitsigns")
require("enoch.lsp")
require("enoch.telescope")
require("enoch.toggleterm")
require("enoch.treesitter")
require("enoch.alpha")
require("enoch.format")
require("enoch.autopairs")
require("enoch.blankline")
require("enoch.lualine")

require("fidget").setup()
