require("enoch.filetree")
require("enoch.gitsigns")
require("enoch.lsp")
require("enoch.telescope")
require("enoch.toggleterm")
require("enoch.treesitter")
require("enoch.format")
require("enoch.lualine")

-- require("fidget").setup()
-- require("leap").set_default_keymaps()
-- require("enoch.alpha")
-- require("enoch.autopairs")
-- require("enoch.cmp")
-- require("enoch.blankline")
