local set = vim.keymap.set
local opts = { noremap = true, silent = true }
set("n", "j", "gj", opts)
set("n", "k", "gk", opts)
set("v", ">", ">gv", opts)
set("v", "<", "<gv", opts)
set("n", "<A-h>", "<C-w><", opts)
set("n", "<A-j>", "<C-w>-", opts)
set("n", "<A-k>", "<C-w>+", opts)
set("n", "<A-l>", "<C-w>>", opts)
set("n", "]b", ":bnext<CR>", opts)
set("n", "[b", ":bprevious<CR>", opts)
set("n", "<leader>d", function()
    return vim.diagnostic.open_float(nil, { focus = false })
end, opts)
set("n", "<C-p>", (require "telescope.builtin").find_files, opts)
set("n", "<C-f>", (require "telescope.builtin").live_grep, opts)
set("n", "<C-b>", (require "telescope.builtin").buffers, opts)
set("n", "<leader>fh", (require "telescope.builtin").help_tags, opts)
set("n", "z=", (require "telescope.builtin").spell_suggest, opts)
set("n", "<leader>o", (require "telescope.builtin").jumplist, opts)
set("n", "<leader>cdg", ":Telescope node-workspace<CR>", opts)
set("n", "<C-n>", ":Explore<CR>", opts)
set("n", "<C-\\>", ":vs|:term<CR>", opts)
set("n", "<leader>nf", ":Neogen<CR>", opts)
set("n", "<leader>w", (require "nvim-window").pick, opts)
