return {
{"The creation of Notepad++ is due to my need for a decent editor to edit the source code of Notepad++", " - Notepad++"},
{"I hate reading other people's code.\nSo I wrote mine, made it as open source project, and watch others suffer.", " - Notepad++ #1"},
{"Good programmers use Notepad++ to code.\nExtreme programmers use MS Word to code, in Comic Sans, center aligned.", " - Notepad++ #2"},
{"The best things in life are free.\nNotepad++ is free.\nSo Notepad++ is the best.\n", " - Notepad++ #3"},
{"If I'm the Father of Open Source, it was conceived through artificial insemination using stolen sperm without my knowledge or consent.", " - Richard Stallman"},
{"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.", " - Martin Golding"},
{"To iterate is human, to recurse divine.", " - L. Peter Deutsch"},
{"The trouble with programmers is that you can never tell what a programmer is doing until it's too late.", " - Seymour Cray"},
{"Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.", " - Brian Kernighan"},
{"Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.", " - Alan Kay"},
{"Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", " - Bill Gates"},
{"Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.", " - Christopher Thompson"},
{"I don't care if it works on your machine! We are not shipping your machine!", " - Vidiu Platon"},
{"Walking on water and developing software from a specification are easy if both are frozen.", " - Edward V Berard"},
{"Fine, Java MIGHT be a good example of what a programming language should be like.\nBut Java applications are good examples of what applications SHOULDN'T be like.", " - pixadel"},
{"I think Microsoft named .Net so it wouldn't show up in a Unix directory listing.", " - Oktal"},
{"In C++ it's harder to shoot yourself in the foot, but when you do, you blow off your whole leg.", " - Bjarne Stroustrup"},
{"Don't worry if it doesn't work right. If everything did, you'd be out of a job.", " - Mosher's Law of Software Engineering"},
{"Writing in C or C++ is like running a chain saw with all the safety guards removed.", " - Bob Gray"},
{"In the one and only true way. The object-oriented version of \"Spaghetti code\" is, of course, \"Lasagna code\". (Too many layers)", " - Roberto Waltman"},
{"C++ : Where friends have access to your private members.", " - Gavin Russell Baker"},
{"Software is like sex: It's better when it's free.", " - Linus Torvalds"},
{"Emacs is a great operating system, lacking only a decent editor.", " - Cult of vi"},
{"vi has two modes - \"beep repeatedly\" and \"break everything\".", " - Church of Emacs"},
{"Picasso had a saying: \"Good artists copy, great artists steal.\".\nWe have always been shameless about stealing great ideas.", " - Steve Jobs"},
{"Do everything for greatness, not money. Money follows greatness.", " - brotips #1001"},
{"God gave men both a penis and a brain, but unfortunately not enough blood supply to run both at the same time.", " - Robin Williams"},
{"Strong people don't put others down.\nThey lift them up.", " - Darth Vader"},
{"You don't get to 500 million star systems without making a few enemies.", " - Darth Vader #2"},
{"A good programmer is someone who always looks both ways before crossing a one-way street.", " - Doug Linder"},
{"A cookie has no soul, it's just a cookie. But before it was milk and eggs.\nAnd in eggs there's the potential for life.", " - Jean-Claude van Damme"},
{"Java is, in many ways, C++--.", " - Michael Feldman"},
{"Je mange donc je chie.", " - Don Ho"},
{"RTFM is the true path of every developer.\nBut it would happen only if there's no way out.", " - Don Ho #2"},
{"Smartphone is the best invention of 21st century for avoiding the eyes contact while crossing people you know on the street.", " - Don Ho #3"},
{"Poor countries' museums vs. rich countries' museums:\nThe first show what they have left.\nThe second show what they have stolen.", " - Don Ho #4"},
{"An opinion without 3.14 is just an onion.", " - Anonymous #1"},
{"Before sex, you help each other get naked, after sex you only dress yourself.\nMoral of the story: in life no one helps you once you're fucked.", " - Anonymous #2"},
{"I'm not totally useless. I can be used as a bad example.", " - Anonymous #3"},
{"Life is too short to remove USB safely.", " - Anonymous #4"},
{"\"SEX\" is not the answer.\nSex is the question, \"YES\" is the answer.", " - Anonymous #5"},
{"Going to McDonald's for a salad is like going to a whore for a hug.", " - Anonymous #6"},
{"I need a six month holiday, TWICE A YEAR!", " - Anonymous #7"},
{"Everything is a knife if you're strong enough.", " - Anonymous #8"},
{"I'M A FUCKING ANIMAL IN BED.\nMore specifically a koala.", " - Anonymous #9"},
{"Etc.\n\n(Abb.) End of Thinking Capacity.\n", " - Anonymous #10"},
{"We stopped checking for monsters under our bed, when we realized they were inside us.", " - Anonymous #11"},
{"I would rather check my facebook than face my checkbook.", " - Anonymous #12"},
{"Whoever says Paper beats Rock is an idiot. Next time I see someone say that I will throw a rock at them while they hold up a sheet of paper.", " - Anonymous #13"},
{"A better world is where chickens can cross the road without having their motives questioned.", " - Anonymous #14"},
{"If I didn't drink, how would my friends know I love them at 2 AM?", " - Anonymous #15"},
{"Q: How do you generate a random string?\nA: Put a Windows user in front of vi, and tell him to exit.", " - Anonymous #16"},
{"Pros and cons of making food.\nPros: food\nCons : making\n", " - Anonymous #17"},
{"Never get into fights with ugly people, they have nothing to lose.", " - Anonymous #18"},
{"People who say they give 110%\ndon't really understand how percentages work.", " - Anonymous #19"},
{"Never make eye contact while eating a banana.", " - Anonymous #20"},
{"I love my sixpack so much, I protect it with a layer of fat.", " - Anonymous #21"},
{"\"It's impossible.\" said pride.\n\"It's risky.\" said experience.\n\"It's pointless.\" said reason.\n\"Give it a try.\" whispered the heart.\n...\n\"What the hell was that?!?!?!?!?!\" shouted the anus two minutes later.", " - Anonymous #22"},
{"A programmer is told to \"go to hell\".\nHe finds the worst part of that statement is the \"go to\".", " - Anonymous #23"},
{"An Architect's dream is an Engineer's nightmare.", " - Anonymous #24"},
{"In a way, I feel sorry for the kids of this generation.\nThey'll have parents who know how to check browser history.", " - Anonymous #25"},
{"Q: What's the difference between git and github?\nA: It's the difference between porn and pornhub.\n", " - Anonymous #26"},
{"I don't have a problem with caffeine.\nI have a problem without caffeine.", " - Anonymous #27"},
{"Why 6 afraid of 7?\nBecause 7 8 9 while 6 and 9 were flirting.", " - Anonymous #28"},
{"How do you comfort a JavaScript bug?\nYou console it.", " - Anonymous #29"},
{"Why do Java developers wear glasses?\nBecause they don't C#.", " - Anonymous #30"},
{"A baby's laughter is one of the most beautiful sounds you will ever hear. Unless it's 3 AM. And you're home alone. And you don't have a baby.", " - Anonymous #31"},
{"Two bytes meet. The first byte asks, \"You look terrible. Are you OK?\"\nThe second byte replies, \"No, just feeling a bit off.\"", " - Anonymous #32"},
{"Programmer - an organism that turns coffee into software.", " - Anonymous #33"},
{"It's not a bug - it's an undocumented feature.", " - Anonymous #34"},
{"Should array index start at 0 or 1?\nMy compromised solution is 0.5", " - Anonymous #35"},
{"Every single time when I'm about to hug someone extremely sexy, I hit the mirror.", " - Anonymous #36"},
{"My software never has bugs. It just develops random features.", " - Anonymous #37"},
{"LISP = Lots of Irritating Silly Parentheses.", " - Anonymous #38"},
{"Perl, the only language that looks the same before and after RSA encryption.", " - Anonymous #39"},
{"People ask me why, as an atheist, I still say: OH MY GOD.\nIt makes perfect sense: We say \"Oh my God\" when something is UNBELIEVABLE.", " - Anonymous #40"},
{"1. Dig a hole.\n2. Name it love.\n3. Watch people falling in love.\n", " - Anonymous #41"},
{"Don't think of yourself as an ugly person.\nThink of yourself as a beautiful monkey.", " - Anonymous #42"},
{"Afraid to die alone?\nBecome a bus driver.", " - Anonymous #43"},
{"The first 5 days after the weekend are always the hardest.", " - Anonymous #44"},
{"Rhinos are just fat unicorns.", " - Anonymous #45"},
{"Sometimes when I'm writing Javascript I want to throw up my hands and say \"this is bullshit!\"\nbut I can never remember what \"this\" refers to.", " - Anonymous #46"},
{"Kids are like farts.\nYou can only stand yours.", " - Anonymous #47"},
{"If you were born in Israel, you'd probably be Jewish.\nIf you were born in Saudi Arabia, you'd probably be Muslim.\nIf you were born in India, you'd probably be Hindu.\nBut because you were born in North America, you're Christian.\nYour faith is not inspired by some divine, constant truth.\nIt's simply geography.", " - Anonymous #48"},
{"There are 2 types of people in this world:\nPeople who say they pee in the shower, and the dirty fucking liars.", " - Anonymous #49"},
{"London 2012 Olympic Games - A bunch of countries coming across the ocean to put their flags in Britain and try to get a bunch of gold... it's like history but opposite.", " - Anonymous #50"},
{"I don't need a stable relationship,\nI just need a stable Internet connection.", " - Anonymous #51"},
{"What's the difference between religion and bullshit?\nThe bull.", " - Anonymous #52"},
{"Today, as I was waiting for my girlfriend in the street, I saw a woman who looked a lot like her. I ran towards her, my arms in the air ready to give her a hug, only to realise it wasn't her. I then had to pass the woman, my arms in the air, still running. FML", " - Anonymous #53"},
{"Decimal: 1 + 1 = 2\nBinary:  1 + 1 = 10\nBoolean: 1 + 1 = 1\nJavaScript(hold my beer) : 1 + 1 = 11\n", " - Anonymous #54"},
{"Don't be ashamed of who you are.\nThat's your parents job.", " - Anonymous #55"},
{"Religion is like circumcision.\nIf you wait until someone is 21 to tell them about it they probably won't be interested.", " - Anonymous #56"},
{"No, no, no, I'm not insulting you.\nI'm describing you.", " - Anonymous #57"},
{"I bought a dog once. Named him \"Stay\".\n\"Come here, Stay.\"\nHe's insane now.", " - Anonymous #58"},
{"Law of Software Quality:\n	errors = (more code)²\ne = mc²", " - Anonymous #59"},
{"Yesterday I named my Wifi network \"hack me if you can\"\nToday when I woke up it was changed to \"challenge accepted\".", " - Anonymous #60"},
{"Your mother is so fat,\nthe recursive function computing her mass causes a stack overflow.", " - Anonymous #61"},
{"Oral sex makes my day, but anal sex makes my hole weak.", " - Anonymous #62"},
{"I'm not saying I am Batman, I am just saying no one has ever seen me and Batman in the same room together.", " - Anonymous #63"},
{"I took a taxi today.\nThe driver told me \"I love my job, I own this car, I've got my own business, I'm my own boss, NO ONE tells me what to do!\"\nI said \"TURN LEFT HERE\".\n", " - Anonymous #64"},
{"A man without God is like a fish without a bicycle.", " - Anonymous #65"},
{"I hate how spiders just sit there on the walls and act like they pay rent!", " - Anonymous #66"},
{"Whenever someone starts a sentence by saying \"I'm not racist...\"),they are about to say something super racist.", " - Anonymous #67"},
{"I'm not laughing at you, I'm laughing with you, you're just not laughing.\n", " - Anonymous #68"},
{"Women need a reason to have sex. Men just need a place.", " - Anonymous #69"},
{"If abortion is murder then are condoms kidnapping?", " - Anonymous #70"},
{"Men also have feelings.\nFor example, they can feel hungry.", " - Anonymous #71"},
{"Project Manager:\nA person who thinks 9 women can deliver a baby in 1 month.", " - Anonymous #72"},
{"If you try and don't succeed, cheat. Repeat until caught. Then lie.", " - Anonymous #73"},
{"Olympics is the stupidest thing.\nPeople are so proud to be competing for their country.\nThey play their stupid song and raise some dumb flags.\nI'd love to see no flags raised, no song, no mention of country.\nOnly people.", " - Anonymous #74"},
{"I think therefore I am\nnot religious.", " - Anonymous #75"},
{"Even if being gay were a choice, so what?\nPeople choose to be assholes and they can get married.", " - Anonymous #76"},
{"Governments are like diapers.\nThey should be changed often, and for the same reason.", " - Anonymous #77"},
{"Mathématiquement, un cocu est un entier qui partage sa moitié avec un tiers.\n", " - Anonymous #78"},
{"I'm a creationist.\nI believe man created God.\n", " - Anonymous #79"},
{"Let's eat kids.\nLet's eat, kids.\n\nUse a comma.\nSave lives.\n", " - Anonymous #80"},
{"A male engineering student was crossing a road one day when a frog called out to him and said, \"If you kiss me, I'll turn into a beautiful princess.\" He bent over, picked up the frog, and put it in his pocket.\n\nThe frog spoke up again and said, \"If you kiss me and turn me back into a beautiful princess, I will stay with you for one week.\" The engineering student took the frog out of his pocket, smiled at it; and returned it to his pocket.\n\nThe frog then cried out, \"If you kiss me and turn me back into a princess, I'll stay with you and do ANYTHING you want.\" Again the boy took the frog out, smiled at it, and put it back into his pocket.\n\nFinally, the frog asked, \"What is the matter? I've told you I'm a beautiful princess, that I'll stay with you for a week and do anything you want. Why won't you kiss me?\" The boy said, \"Look I'm an engineer. I don't have time for a girlfriend, but a talking frog is cool.\"\n", " - Anonymous #81"},
{"Gamers never die.\nThey just go offline.\n", " - Anonymous #82"},
{"Copy from one, it's plagiarism.\nCopy from two, it's research.\n", " - Anonymous #83"},
{"Saying that Java is nice because it works on all OSes is like saying that anal sex is nice because it works on all genders.", " - Anonymous #84"},
{"Race, religion, ethnic pride and nationalism etc... does nothing but teach you how to hate people that you've never met.", " - Anonymous #85"},
{"Farts are just the ghosts of the things we eat.", " - Anonymous #86"},
{"I promised I would never kill someone who had my blood.\nBut that mosquito made me break my word.", " - Anonymous #87"},
{"Si un jour une chaise te dit que t'as un joli cul, tu trouveras ça bizarre mais c'est juste un compliment d'objet direct.", " - Anonymous #88"},
{"The biggest step in any relationship isn't the first kiss.\nIt's the first fart.", " - Anonymous #89"},
{"Clapping:\n(verb)\nRepeatedly high-fiving yourself for someone else's accomplishments.", " - Anonymous #90"},
{"CV: ctrl-C, ctrl-V", " - Anonymous #91"},
{"Mondays are not so bad.\nIt's your job that sucks.", " - Anonymous #92"},
{"[In a job interview]\nInterviewer: What's your greatest weakness?\nCandidate: Honesty.\nInterviewer: I don't think honesty is a weakness.\nCandidate: I don't give a fuck what you think.", " - Anonymous #93"},
{"Hey, I just met you\nAnd this is crazy\nHere's my number 127.0.0.1\nPing me maybe?", " - Anonymous #94"},
{"What if the spider you killed in your house had spent his entire life thinking you were his roommate?\nEver think about that?\nNo. You only think about yourself.\n", " - Anonymous #95"},
{"Code for 6 minutes, debug for 6 hours.", " - Anonymous #96"},
{"Real Programmers don't comment their code.\nIf it was hard to write, it should be hard to read.", " - Anonymous #97"},
{"My neighbours listen to good music.\nWhether they like it or not.", " - Anonymous #98"},
{"I've been using Vim for about 2 years now,\nmostly because I can't figure out how to exit it.", " - Anonymous #99"},
{"Dear YouTube,\nI can deal with Ads.\nI can deal with Buffer.\nBut when Ads buffer, I suffer.", " - Anonymous #100"},
{"It's always sad when a man and his dick share only one brain...\nand it turns out to be the dick's.", " - Anonymous #101"},
{"If IE is brave enough to ask you to set it as your default browser,\ndon't tell me you dare not ask a girl out.", " - Anonymous #102"},
{"The main idea of \"Inception\":\nif you run a VM inside a VM inside a VM inside a VM inside a VM,\neverything will be very slow.", " - Anonymous #104"},
{"The best antivirus is common sense.", " - Anonymous #105"},
{"When I die, I want to go peacefully like my grandfather did, in his sleep\n- not screaming, like the passengers in his car.", " - Anonymous #106"},
{"Remember, YOUR God is real.\nAll those other Gods are ridiculous, made-up nonsense.\nBut not yours.\nYour God is real. Whichever one that is.", " - Anonymous #107"},
{"#your-mom {\n	width: 100000000000000000000px;\n	float: nope;\n}\n", " - Anonymous #108"},
{"What's the best thing about UDP jokes?\nI don't care if you get them.", " - Anonymous #109"},
{"A programmer had a problem, so he decided to use threads.\nNow 2 has. He problems", " - Anonymous #110"},
{"I'VE NEVER BEEN VERY GOOD AT GEOGRAPHY.\nBUT I CAN NAME AT LEAST ONE CITY IN FRANCE, WHICH IS NICE.", " - Anonymous #111"},
{"#hulk {\n    height: 200%;\n    width: 200%;\n    color: green;\n}\n", " - Anonymous #112"},
{"A colon can completely change the meaning of a sentence. For example:\n- Jane ate her friend's sandwich.\n- Jane ate her friend's colon.", " - Anonymous #113"},
{"How can you face your problem if your problem is your face?", " - Anonymous #114"},
{"YOLOLO:\nYou Only LOL Once.", " - Anonymous #115"},
{"Every exit is an entrance to new experiences.", " - Anonymous #116"},
{"A Native American was asked:\n\"Do you celebrate Columbus day?\"\nHe replied:\n\"I don't know, do Jews celebrate Hitler's birthday?\"", " - Anonymous #117"},
{"I love necrophilia, but i can't stand the awkward silences.", " - Anonymous #118"},
{"\"I'm gonna Google that. BING that, Bing that, sorry.\"\n- The CEO of Bing (many times per day still)", " - Anonymous #119"},
{"GRAMMAR\nThe difference between knowing your shit and knowing you're shit.", " - Anonymous #120"},
{"5 out of 6 people agree that Russian roulette is completely safe.", " - Anonymous #121"},
{"Nerd?\nI prefer the term \"Intellectual badass\".", " - Anonymous #122"},
{"I know every digit of π,\njust not in the right order.", " - Anonymous #123"},
{"You don't need religion to have morals.\nIf you can't determine right from wrong then you lack empathy, not religion.", " - Anonymous #124"},
{"Pooping with the door opened is the meaning of true freedom.", " - Anonymous #125"},
{"Social media does not make people stupid.\nIt just makes stupid people more visible.", " - Anonymous #126"},
{"SELECT finger\nFROM hand\nWHERE id = 2 ;\n", " - Anonymous #127"},
{"3 men are on a boat. They have 4 cigarettes, but nothing to light them with.\nSo they throw a cigarette overboard and the whole boat becomes a cigarette lighter.", " - Anonymous #128"},
{"What is the most used language in programming?\n\nProfanity\n", " - Anonymous #129"},
{"Common sense is so rare, it's kinda like a superpower...", " - Anonymous #130"},
{"The best thing about a boolean is even if you are wrong, you are only off by a bit.", " - Anonymous #131"},
{"Benchmarks don't lie, but liars do benchmarks.", " - Anonymous #132"},
{"Multitasking: Screwing up several things at once.", " - Anonymous #133"},
{"Linux is user friendly.\nIt's just picky about its friends.", " - Anonymous #134"},
{"Theory is when you know something, but it doesn't work.\nPractice is when something works, but you don't know why.\nProgrammers combine theory and practice: nothing works and they don't know why.", " - Anonymous #135"},
{"Documentation is like sex:\nwhen it's good, it's very, very good;\nwhen it's bad, it's better than nothing.", " - Anonymous #136"},
{"Home is where you poop most comfortably.", " - Anonymous #137"},
{"Laptop Speakers problem: too quiet for music, too loud for porn.", " - Anonymous #138"},
{"Chinese food to go: $16\nGas to go get the food: $2\nDrove home just to realize they forgot one of your containers: RICELESS", " - Anonymous #139"},
{"MS Windows is like religion to most people: they are born into it, accept it as default, never consider switching to another.", " - Anonymous #140"},
{"To most religious people, the holy books are like a software license (EULA).\nNobody actually reads it. They just scroll to the bottom and click \"I agree\".", " - Anonymous #141"},
{"You are nothing but a number of days,\nwhenever each day passes then part of you has gone.", " - Anonymous #142"},
{"If 666 is evil, does that make 25.8069758011 the root of all evil?", " - Anonymous #143"},
{"I don't want to sound like a badass but\nI eject my USB drive without removing it safely.", " - Anonymous #144"},
{"feet  (noun)\na device used for finding legos in the dark", " - Anonymous #145"},
{"Buy a sheep\nName it \"Relation\"\nNow you have a Relationsheep\n", " - Anonymous #146"},
{"I dig, you dig, we dig,\nhe dig, she dig, they dig...\n\nIt's not a beautiful poem,\nbut it's very deep.", " - Anonymous #147"},
{"# UNIX command line Russian roulette:\n[ $[ $RANDOM % 6 ] == 0 ] && rm -rf /* || echo *Click*\n", " - Anonymous #148"},
{"unzip, strip, top, less, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, fsck, umount, sleep.\n\nNo, it's not porn. It's Unix.", " - Anonymous #149"},
{"To understand what recursion is, you must first understand recursion.", " - Anonymous #150"},
{"Q: What's the object-oriented way to become wealthy?\nA: Inheritance.", " - Anonymous #151"},
{"A SQL query goes into a bar, walks up to two tables and asks, \"Can I join you?\"", " - Anonymous #152"},
{"You are not fat, you are just more visible.", " - Anonymous #153"},
{"Minimalist\n (.   .)\n  )   (\n (  Y  )\nASCII Art", " - Anonymous #154"},
{"Parallel lines have so much in common...\nIt's a shame that they'll never meet.", " - Anonymous #155"},
{"Declare variables, not war.\nExecute programs, not people.", " - Anonymous #156"},
{"I can't see an end. I have no control and I don't think there's any escape. I don't even have a home anymore.\nI think it's time for a new keyboard.", " - Anonymous #157"},
{"6.9\nA little fun interrupted by a period.", " - Anonymous #158"},
{"I love anal\n-yzing all data before making assumptions.", " - Anonymous #159"},
{"So my wife said\n\"take off my shirt\".\nI did as she said and take off her shirt.\nThen she said,\n\"Take off my skirt.\"\nI took off her skirt.\n\"Take off my shoes.\"\nI took off her shoes.\n\"Now take off my bra and panties.\"\nand so I took them off.\nThen she looked at me and said\n\"I don't want to catch you wearing my things ever again.\"", " - Anonymous #160"},
{"Do you know:\nSpiders are the only web developers in the world that enjoy finding bugs.", " - Anonymous #161"},
{"Psychologist: Lie down please.\n8: No, thank you. If I do, this session will never reach the end.", " - Anonymous #162"},
{"I love the way the earth rotates,\nit really makes my day.", " - Anonymous #163"},
{"Homonyms are a waist of thyme.", " - Anonymous #164"},
{"What's the difference between a police officer and a bullet?\nWhen a bullet kills someone else, you know it's been fired.", " - Anonymous #165"},
{"What has 4 letters\nsometimes 9 letters\nbut never has 5 letters", " - Anonymous #166"},
{"The 'h' in \"software development\" stands for \"happiness\".", " - Anonymous #167"},
{"Never let your computer know that you are in a hurry.\nComputers can smell fear.\nThey slow down if they know that you are running out of time.", " - Anonymous #168"},
{"JavaScript is not a language.\nIt's a programming jokes generator.", " - Anonymous #169"},
{"A journalist asked Linus Torvalds what makes code bad.\nHe replied : No comment.", " - Anonymous #170"},
{"If you spell \"Nothing\" backwards, it becomes \"Gnihton\" which also means nothing.", " - Anonymous #171"},
{"Programming in Javascript is like looking both ways before you cross the street, and then getting hit by an airplane.", " - Anonymous #172"},
{"Q: Why do we need a backend, why not just connect front end to database???\n\nA: Yeah! And why do we eat and go to the bathroom while we can throw the food directly in the toilet? Because stuff needs to get processed. ;)\n", " - Anonymous #173"},
{"Someday, once humans are extinct from covid-19. I hope whatever species rules Earth makes chicken nuggets in the shape of us, like we did for dinosaurs.", " - Anonymous #174"},
{"Linkedin is basically a reversed Tinder.\nHot girls write to nerd guys and they didn't reply.", " - Anonymous #175"},
{"A vegan said to me, \"people who sell meat are gross!\"\nI said, \"people who sell fruits and vegetables are grocer.\"\n", " - Anonymous #176"},
{"Documentation is a love letter that you write to your future self.\n", " - Anonymous #177"},
{"When I die, I hope it's early in the morning so I don't have to go to work that day for no reason.\n", " - Anonymous #178"},
{"Workers plaay football\nManagers play tennis\nCEOs play golf\n\nHigher the function, smaller the balls.\n", " - Anonymous #179"},
{"Friends are just like trees.\nThey fall down when you hit them multiple times with an axe.\n", " - Anonymous #180"},
{"I met a magical Genie. He gave me one wish.\nI said: \"I wish I could be you.\"\nThe Genue saud: \"Weurd wush but U wull grant ut.\"\n", " - Anonymous #181"},
{"printf(\"%s%s\", \"\\\\o/\\n| |\\n| |8=\", \"=D\\n/ \\\\\\n\");\n", " - Anonymous #182"},
{"Dear Optimist, Pessimist and Realist,\n\nWhile you guys were busy arguing about\nthe glass of water, I drank it!\n\n\n					Sincerely,\n					The Opportunist\n", " - Anonymous #183"},
{"Dance like nobody's watching.\nEncrypt like everyone is.\n", " - Anonymous #184"},
{"Me: \"I'm 45 years old but I've got a 19 year-old young man's body\"\nHer: \"Show me\"\nI opened the freezer to show her the body.\nShe screamed.\nMe too.\n", " - Anonymous #185"},
{"Everyone complains about the weather,\nbut no one wants to sacrifice a virgin to change it.\n", " - Anonymous #186"},
{"If you are alone at home and feel lonely:\nTurn off the lights, turn on the TV and watch a horror movie.\nThen you will have feeling that there are someone hidden in the kitchen, in the toilet\nand even under your bed.\n", " - Anonymous #187"},
{"*Knock knock*\n\"Race condition\"\n\"Who's there?\"\n", " - Anonymous #188"},
{"The two most difficult programming challenges are naming things, cache invalidation, and off-by-one errors.\n", " - Anonymous #189"},
{"The greatest security vulnerability in any computer system is located between the keyboard and the chair.\n", " - Anonymous #190"},
{"My biggest talent is always being able to tell what's in a wrapped present.\n\nIt's a gift.\n", " - Anonymous #191"},
{"You can't force someone to love you.\nBut you can lock this person in the basement and wait for him/her to develop Stockholm syndrome.\n", " - Anonymous #192"},
{"Do you know:\nthere are more airplanes in the oceans, than submarines in the sky?\n", " - Anonymous #193"},
{"If you hold a Unix shell up to your ear,\nyou might just be able to hear the C.\n", " - Anonymous #194"},
{"Why do programmers always mix up Halloween and Christmas?\nBecause Oct 31 == Dec 25\n", " - Anonymous #195"},
{"What happened to the function that ran away?\nIt never returned.\n", " - Anonymous #196"},
{"When I am tasked with sorting through a stack of résumés, I throw about half of them in the garbage.\nI do not want unlucky people working in our company.\n", " - Anonymous #197"},
{"The reason why we write SQL commands all in CAPITAL letters is because it stands for Screaming Query Language.\n", " - Anonymous #198"},
{"Never have I felt so close to another soul\nAnd yet so helplessly alone\nAs when I Google an error\nAnd there's one result\nA thread by someone with the same problem\nAnd no answer\nLast posted to in 2003\n\n\"Who were you, DenverCoder9?\"\n\"What did you see?!\"\n\n(ref: https://xkcd.com/979/)", " - xkcd"},
{"No hugs & kisses.\nOnly bugs & fixes.", " - A developer"},
{"Don't set your password as your child's name.\nName your child after your password.", " - Elon Musk"},
{"If you want to treat women as objects,\ndo it with class.", " - OOP"},
{"Quote not Found", " - Internet #404"},
{"Someone I loved once gave me a box full of darkness.\nIt took me years to understand that this, too, was a gift.", " - Mary Oliver"},
{"If you fall, I will be there.", " - Floor"},
{"If you have some problem in your life and need to deal with it, then use religion, that's fine.\nI use Google.", " - Simon Amstell"},
{"Only 3 things are infinite:\n1. Universe.\n2. Human Stupidity.\n3. Winrar's free trial.", " - Albert Einstein"},
{"Artificial Intelligence is no match for natural stupidity.", " - Terry Pratchett"},
{"Once a new technology starts rolling, if you're not part of the steamroller,\nyou're part of the road.", " - Stewart Brand"},
{"Software and cathedrals are much the same - first we build them, then we pray.", " - Sam Redwine"},
{"In theory, there is no difference between theory and practice. But, in practice, there is.", " - Jan L. A. van de Snepscheut"},
{"One man's crappy software is another man's full time job.", " - Jessica Gaston"},
{"Mon pied droit est jaloux de mon pied gauche. Quand l'un avance, l'autre veut le dépasser.\nEt moi, comme un imbécile, je marche !", " - Raymond Devos"},
{"int getRandomNumber()\n{\n    return 4; //chosen by fair dice roll, guaranteed to be random.\n}\n", " - xkcd.com"},
{"Earth provides enough to satisfy every man's need, but not every man's greed.", " - Gandhi"},
{"Life is a sexually transmitted disease and the mortality rate is one hundred percent.", " - R. D. Laing"},
{"Politicians are like sperm.\nOne in a million turn out to be an actual human being.", " - Hustle Man"},
{"Censorship is telling a man he can't have a steak just because a baby can't chew it.", " - Mark Twain"},
{"There is not enough love and goodness in the world to permit giving any of it away to imaginary beings.", " - Friedrich Nietzsche"},
{"Pain is a state of mind and I don't mind your pain.", " - Dhalsim"},
{"Human beings can be beautiful or more beautiful,\nthey can be fat or skinny, they can be right or wrong,\nbut illegal? How can a human being be illegal?", " - Elie Wiesel"},
{"Empty your memory, with a free(), like a pointer.\nIf you cast a pointer to a integer, it becomes the integer.\nIf you cast a pointer to a struct, it becomes the struct.\nThe pointer can crash, and can overflow.\nBe a pointer my friend.", " - Dennis Ritchie"},
{"Uuuuuuuuuur Ahhhhrrrrrr\nUhrrrr Ahhhhrrrrrr\nAaaarhg...", " - Chewbacca"},
{"No one ever makes a billion dollars.\nYou TAKE a billion dollars.", " - Alexandria Ocasio-Cortez"},
{"Never stop dreaming.\n", " - Freddy Krueger"},
{"Feel free to mock my lack of belief in any Gods.\nIt won't hurt my feelings.\nIt won't damage my faith in reason.\nAnd I won't kill you for it.", " - Ricky Gervais"},
{"Knowledge is power. France is bacon.\n\nWhen I was young my father said to me: \"Knowledge is power, Francis Bacon.\" I understood it as \"Knowledge is power, France is bacon.\"\n\nFor more than a decade I wondered over the meaning of the second part and what was the surreal linkage between the two. If I said the quote to someone, \"Knowledge is power, France is Bacon\", they nodded knowingly. Or someone might say, \"Knowledge is power\" and I'd finish the quote \"France is Bacon\" and they wouldn't look at me like I'd said something very odd, but thoughtfully agree. I did ask a teacher what did \"Knowledge is power, France is bacon\" mean and got a full 10-minute explanation of the \"knowledge is power\" bit but nothing on \"France is bacon\". When I prompted further explanation by saying \"France is bacon?\" in a questioning tone I just got a \"yes\". At 12 I didn't have the confidence to press it further. I just accepted it as something I'd never understand.\n\nIt wasn't until years later I saw it written down that the penny dropped.\n", " - Francis bacon"},
{"\n\n       ▄██▄\n     ▄██████▄           █   █  █▀▀▀\n     ██▄██▄██           █   █  █▄▄\n      ▄▀▄▄▀▄            █ █ █  █\n     ▀ ▀  ▀ ▀           ▀▀ ▀▀  ▀▀▀▀\n\n      ▀▄   ▄▀           ▄█▀▀▀  ▄█▀▀█▄  █▀▄▀█  █▀▀▀\n     ▄█▀███▀█▄          █      █    █  █ ▀ █  █▄▄\n    █ █▀▀▀▀▀█ █         █▄     █▄  ▄█  █   █  █\n       ▀▀ ▀▀             ▀▀▀▀   ▀▀▀▀   ▀   ▀  ▀▀▀▀\n\n     ▄▄█████▄▄          ▀█▀  █▀▄  █\n    ██▀▀███▀▀██          █   █ ▀▄ █\n    ▀▀██▀▀▀██▀▀          █   █  ▀▄█\n    ▄█▀ ▀▀▀ ▀█▄         ▀▀▀  ▀   ▀▀\n\n      ▄▄████▄▄          █▀▀█  █▀▀▀  ▄▀▀▄  ▄█▀▀▀  █▀▀▀\n    ▄██████████▄        █▄▄█  █▄▄   █▄▄█  █      █▄▄ \n  ▄██▄██▄██▄██▄██▄      █     █     █  █  █▄     █   \n    ▀█▀  ▀▀  ▀█▀        ▀     ▀▀▀▀  ▀  ▀   ▀▀▀▀  ▀▀▀▀\n\n", " - Space Invaders"},
{"Freedom of expression is like the air we breathe, we don't feel it, until people take it away from us.\n\nFor this reason, Je suis Charlie, not because I endorse everything they published, but because I cherish the right to speak out freely without risk even when it offends others.\nAnd no, you cannot just take someone's life for whatever he/she expressed.\n\nHence this \"Je suis Charlie\" edition.\n", " - #JeSuisCharlie"},
}
