local treesitter = require "nvim-treesitter.configs"
local langs = {
    "bash",
    "comment",
    "css",
    "dockerfile",
    "dot",
    "fennel",
    "go",
    "graphql",
    "hcl",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "jsonc",
    "julia",
    "lua",
    "query",
    "regex",
    "scss",
    "svelte",
    "tsx",
    "typescript",
    "vim",
    "yaml",
    "zig",
}

treesitter.setup {
    ensure_installed = langs,
    sync_install = false,
    highlight = { enable = true, additional_vim_regex_highlighting = false },
    autotag = { enable = true },
    context_commentstring = { enable = true },
}
